In [1]:
import pandas as pd
import numpy as np

# Compiling the NDVI csvs

In [4]:
years = [2002,2006,2010,2014,2018,2022]

In [6]:
locations = pd.read_csv('../csv_folder/total_centrepoints.csv')

In [23]:
for year in years:
    ndvis_2002 = pd.read_csv(f'../ndvi_csvs/ndvis2002.csv')
    ndvis_values = pd.read_csv(f'../ndvi_csvs/ndvis{year}.csv')
    ndvis_values = ndvis_values[f'{year}'] - ndvis_2002['2002']
    locations[f'{year}'] = ndvis_values
locations = locations[['longitude','latitude','2002','2006','2010','2014','2018','2022']]
locations.to_csv('../csv_folder/ndvi_results.csv')

In [24]:
ndvis = pd.read_csv('../csv_folder/ndvi_results.csv')
ndvis

,Unnamed: 0,longitude,latitude,2002,2006,2010,2014,2018,2022
0,0,-109.0000,37.0000,0.0,1.074828,10.394136,9.192911,3.983588,2.083432
1,1,-109.0000,37.0427,0.0,1.003137,7.625445,6.565298,1.684776,0.542336
2,2,-109.0000,37.0854,0.0,1.111469,9.325446,5.412403,0.787154,0.638189
3,3,-109.0000,37.1281,0.0,1.633740,11.018625,7.373901,-0.067022,1.128570
4,4,-109.0000,37.1708,0.0,14.944760,23.934974,16.822075,12.488742,2.818820
...,...,...,...,...,...,...,...,...,...
15411,15411,-102.0399,40.8003,0.0,-41.406149,10.210430,2.105374,4.694180,-32.509570
15412,15412,-102.0399,40.8430,0.0,-11.851243,28.168151,30.338278,35.832829,-14.940584
15413,15413,-102.0399,40.8857,0.0,-33.939727,14.770320,18.492895,-2.939644,-16.899683
15414,15414,-102.0399,40.9284,0.0,-4.979792,56.639428,39.758895,35.213647,0.951603
15415,15415,-102.0399,40.9711,0.0,-21.497418,42.431921,22.260549,31.723149,-16.544011

# Turning RGBA images to RGB for the prediction demo

In [26]:
from PIL import Image

In [39]:
for year in years:
    image = Image.open(f'../raw_data/prediction/ndvi_{year}_26.43_45.5.png')
    
    if np.asarray(image).shape  == (512,512,2):
        image = image.convert('L')
        image.save(f'../raw_data/prediction/ndvi_{year}_26.43_45.5.png')